# NumPy Basic

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.19.5


In [3]:
# horizontal 1D array
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [4]:
# vertical 1D array
arr = np.array([[1],[2],[3]])
arr

array([[1],
       [2],
       [3]])

In [5]:
arr = np.array([(1,2,3),(3,4,5)])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [6]:
arr = np.array([[(1,2,3),(3,4,5)] , [(1,2,3),(3,4,5)]])
arr

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [7]:
arr = np.array([[(1,2,3),(3,4,5)] , [(1,2,3),(3,4,5)] , [(1,2,3),(3,4,5)]])
arr

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [11]:
arr = np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
arr = np.zeros((3,3), dtype='int')
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [13]:
arr = np.zeros((3,3), dtype='uint8')
arr

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [14]:
arr = np.ones((3,5), dtype='uint8')
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [15]:
arr = np.full((3,5), 5)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [16]:
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr = np.arange(0,10,6)
arr

array([0, 6])

In [19]:
arr = np.linspace(0,2,9)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [20]:
arr = np.random.rand(2,3)
arr

array([[0.32825052, 0.85061037, 0.27383947],
       [0.72924387, 0.59563827, 0.00636145]])

In [21]:
arr = np.random.rand(2,3)*255
arr

array([[119.02472834, 161.33927794,   9.47505728],
       [ 13.59291231, 214.86165174,  58.20189917]])

In [23]:
arr = np.random.randint(5,size=(3,3))
arr

array([[0, 2, 3],
       [2, 2, 0],
       [2, 0, 2]])

In [24]:
arr = np.array([(1,2,3),(3,4,5)])
arr.shape

(2, 3)

In [25]:
arr = np.array([(1,2,3),(3,4,5)])
arr.size

6

In [26]:
arr = np.array([(1,2,3),(3,4,5)])
arr.dtype

dtype('int32')

In [27]:
arr = np.array([(1.9,2,3),(3,4,5)])
arr.dtype

dtype('float64')

In [28]:
arr = np.array([(1,2,3),(3,4,5)])
arr1 = arr.astype(float)
arr1.dtype

dtype('float64')

In [29]:
arr = np.array([(1,2,3),(3,4,5)])
arr1 = np.array([(1,2,3),(3,4,5)])
arr_f = arr+arr1
arr_f

array([[ 2,  4,  6],
       [ 6,  8, 10]])

In [30]:
arr_f2 = arr_f+20
arr_f2

array([[22, 24, 26],
       [26, 28, 30]])

In [32]:
arr_f2.min()

22

In [33]:
arr = np.array([1,2,3])
arr[1]

2

In [34]:
arr = np.array([(1,2,3),(3,4,5)])
arr[1][1]

4

In [35]:
arr = np.array([(1,2,3,4),(14,3,4,5)])
arr

array([[ 1,  2,  3,  4],
       [14,  3,  4,  5]])

In [36]:
arr[:,0]

array([ 1, 14])

In [37]:
arr[0,:]

array([1, 2, 3, 4])

In [38]:
arr[0,:3]

array([1, 2, 3])

In [39]:
arr[0,1:3]

array([2, 3])

In [40]:
arr = np.array([(1,2,3,4),(14,3,4,5)])
arr

array([[ 1,  2,  3,  4],
       [14,  3,  4,  5]])

In [43]:
arr[::-1]

array([[14,  3,  4,  5],
       [ 1,  2,  3,  4]])

In [45]:
arr.reshape(1,8)

array([[ 1,  2,  3,  4, 14,  3,  4,  5]])

In [48]:
arr = np.arange(1,10)
print(arr)
arr1 = arr.reshape(3,3)
arr1

[1 2 3 4 5 6 7 8 9]


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.append(arr,80)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 80])

In [50]:
arr1 = np.delete(arr,1)
arr1

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr1 = arr.ravel()
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [55]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.array([1,2,3])
print(np.concatenate((arr,arr1)))

[ 1  2  3  4  5  6  7  8  9 10  1  2  3]


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = np.array([1,2,3])
print(np.concatenate((arr1,arr1)))

In [56]:
arr = np.array([(1,2,3),(3,4,5)])
arr

array([[1, 2, 3],
       [3, 4, 5]])

In [58]:
arr.transpose()

array([[1, 3],
       [2, 4],
       [3, 5]])

In [59]:
print(np.transpose(arr))

[[1 3]
 [2 4]
 [3 5]]


In [60]:
arr = np.array([(1,2,3),(3,4,5)])
arr1 = np.copy(arr)
arr1

array([[1, 2, 3],
       [3, 4, 5]])